# Generated by Django 5.0 on 2024-08-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_card_portfolios',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='root'),
        ),
        migrations.AlterField(
            model_name='portfolios_children',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='root'),
        ),
        migrations.AlterField(
            model_name='specialservice',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='root'),
        ),
    ]
